spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8889
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
#        include: health,info,refresh,busrefresh
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name: order.queue
  routing:
    key: order.tracking


#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  datasource:
#    url: jdbc:postgresql://localhost:5432/orderdb
#    username: postgres
#    password: admin
#  datasource:
#    url: jdbc:mysql://localhost:3306/orderdb
#    username: navsingh3211
#    password: yourpassword
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQLDialect
#    properties:
#      hibernate:
#        format_sql: true
#
#
#server:
#  port: 8080

#Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based

#1. Calls happen → monitored (last 10 req)
#2. If ≥50% fail → OPEN state
#3. Block calls for 10 seconds
#4. Allow 3 test calls (HALF-OPEN)
#5. If success → CLOSE
#6. If fail → OPEN again

